### ISSUE TITLE
"continue" is a method of scala.actors.Actor

### ISSUE THREAD

**Issue by quantumdude836** [jodersky/sims#1]
The two actor classes in `src/graphyx/actors` declare a variable called `continue`. However, `continue` is a method defined by the base class `scala.actors.Actor` (Scala version 2.9.2). A simple rename (to e.g. `shouldContinue`) should fix the compile errors.

**Comment by jodersky** [comment]
The latest supported scala version is 2.8, I'm not sure the name conflict is the only bug preventing an update to a higher version though. If you get it working, feel free to submit a PR.

By the way, although I created the project in github just recently (used to be on sourceforge), sims is very old and is mostly unmaintained.

**Comment by jodersky** [comment]
Actually, I just ported it to scala 2.11, including an sbt build.
